# Generated by Django 4.2.5 on 2023-10-02 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipManager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipaddress',
            name='broadcast_address',
        ),
        migrations.RemoveField(
            model_name='ipaddress',
            name='network_address',
        ),
        migrations.RemoveField(
            model_name='ipaddress',
            name='subnet_mask',
        ),
    ]
