# Generated by Django 4.2.5 on 2023-10-05 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipManager', '0005_alter_ipaddress_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ipaddress',
            table='ipmanager_ipaddress',
        ),
    ]
